services:

  mysql:
    image: mysql:latest
    container_name: mysql-latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306

  redis:
    image: redis:alpine
    container_name: redis-alpine
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./data/redis:/data
